services:
  web:
    build: .
    ports:
      - "${APP_PORT}:5000"
    volumes:
      - splitflap-settings:/code/data
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /code
        - action: rebuild
          path: requirements.txt

volumes:
  splitflap-settings:
